Collaboration footer block
drupalpune/campsite pull request #122
Opened 2023-07-18 13:27 UTC by abhisekmazumdar

This resolves https://github.com/drupalpune/campsite/issues/117

2023-07-18 13:28 UTC, abhisekmazumdar commented on config/block.block.in_collaboration_with_siu.yml
> +    - 'block_content:basic:80017529-3aaa-41ed-bd30-f1b76f4300f1'
This is pointing to this content in prod: https://camp2023.drupalpune.in/block/26?destination=/admin/structure/block/block-content

2023-07-18 13:33 UTC, abhisekmazumdar commented on .ddev/providers/acquia.yaml
> +  database_name: drupalcamppune
I shipped this changes here as I think this will be useful in future. If we keep the same code base for next camps. Else I can remove it as needed.

2023-07-19 04:39 UTC, dipakmdhrm requested changes

2023-07-19 04:39 UTC, dipakmdhrm commented on .ddev/providers/acquia.yaml
> +  database_name: drupalcamppune
@abhisekmazumdar Please remove these. DB name is different on live. I think it's camp23 or something. Even so, let's not add these changes in this PR. Let's move every change in the `.ddev` directory in this PR to a new one.

2023-07-19 06:40 UTC, dipakmdhrm approved these changes

2023-07-19 06:40 UTC, merged